import bubbleSort from '../sorting_algorithms/BubbleSort';
import quickSort from '../sorting_algorithms/QuickSort';
import insertionSort from '../sorting_algorithms/InsertionSort';
import selectionSort from '../sorting_algorithms/SelectionSort';
import cocktailShakerSort from '../sorting_algorithms/CocktailShakerSort';
import mergeSort from '../sorting_algorithms/MergeSort';
import radixSort from '../sorting_algorithms/RadixSort';
import introSort from '../sorting_algorithms/IntroSort';
import heapSort from '../sorting_algorithms/HeapSort';
import blockSort from '../sorting_algorithms/BlockSort';
import shellSort from '../sorting_algorithms/ShellSort';
import timSort from '../sorting_algorithms/TimSort';
import exchangeSort from '../sorting_algorithms/ExchangeSort';
import cycleSort from '../sorting_algorithms/CycleSort';
import patienceSort from '../sorting_algorithms/PatienceSort';
import smoothSort from '../sorting_algorithms/SmoothSort';
import strandSort from '../sorting_algorithms/StrandSort.js';
import combSort from '../sorting_algorithms/CombSort';
import gnomeSort from '../sorting_algorithms/GnomeSort';
import oddEvenSort from '../sorting_algorithms/OddEvenSort';
import pigeonholeSort from '../sorting_algorithms/PigeonholeSort';
import bucketSort from '../sorting_algorithms/BucketSort';
import countingSort from '../sorting_algorithms/CountingSort';
import spreadSort from '../sorting_algorithms/SpreadSort';
import pancakeSort from '../sorting_algorithms/PancakeSort';
import iCantBelieveItCanSort from '../sorting_algorithms/ICantBelieveItCanSort';
import bitonicSort from '../sorting_algorithms/BitonicSort';
import bogoSort from '../sorting_algorithms/BogoSort';
import stoogeSort from '../sorting_algorithms/StoogeSort';
import slowSort from '../sorting_algorithms/SlowSort';
import stalinSort from '../sorting_algorithms/StalinSort';
import sleepSort from '../sorting_algorithms/SleepSort';
import deleteSort from '../sorting_algorithms/DeleteSort';
import treeSort from '../sorting_algorithms/TreeSort';

const algorithms = [
  {
    name: 'Bubble Sort',
    function: bubbleSort,
    worseCase: 'n²',
    averageCase: 'n²',
    bestCase: 'n',
    memory: '1',
    stable: true,
    method: 'Exchanging',
    joke: false,
  },
  {
    name: 'Quick Sort',
    function: quickSort,
    worseCase: 'n²',
    averageCase: 'n log(n)',
    bestCase: 'n log(n)',
    memory: 'log(n)',
    stable: false,
    method: 'Partitioning',
    joke: false,
  },
  {
    name: 'Merge Sort',
    function: mergeSort,
    worseCase: 'n log(n)',
    averageCase: 'n log(n)',
    bestCase: 'n log(n)',
    memory: 'n',
    stable: false,
    method: 'Merging',
    joke: false,
  },
  {
    name: 'Insertion Sort',
    function: insertionSort,
    worseCase: 'n²',
    averageCase: 'n²',
    bestCase: 'n',
    memory: '1',
    stable: true,
    method: 'Insertion',
    joke: false,
  },
  {
    name: 'Selection Sort',
    function: selectionSort,
    worseCase: 'n²',
    averageCase: 'n²',
    bestCase: 'n²',
    memory: '1',
    stable: false,
    method: 'Selection',
    joke: false,
  },
  {
    name: 'Cocktail Shaker Sort',
    function: cocktailShakerSort,
    worseCase: 'n²',
    averageCase: 'n²',
    bestCase: 'n',
    memory: '1',
    stable: true,
    method: 'Exchanging',
    joke: false,
  },
  {
    name: 'Radix Sort',
    function: radixSort,
    worseCase: 'nk/d',
    averageCase: 'nk/d',
    bestCase: 'n',
    memory: 'n+2ᵈ',
    stable: true,
    method: 'Non-comparative',
    joke: false,
  },
  {
    name: 'Intro Sort',
    function: introSort,
    worseCase: 'n log(n)',
    averageCase: 'n log(n)',
    bestCase: 'n log(n)',
    memory: 'log(n)',
    stable: false,
    method: 'Hybrid',
    joke: false,
  },
  {
    name: 'Heap Sort',
    function: heapSort,
    worseCase: 'n log(n)',
    averageCase: 'n log(n)',
    bestCase: 'n log(n)',
    memory: '1',
    stable: false,
    method: 'Selection',
    joke: false,
  },
  {
    name: 'Tree Sort',
    function: treeSort,
    worseCase: 'n log(n)',
    averageCase: 'n log(n)',
    bestCase: 'n log(n)',
    memory: 'n',
    stable: true,
    method: 'Insertion',
    joke: false,
  },
  {
    name: 'Block Sort',
    function: blockSort,
    worseCase: 'n log(n)',
    averageCase: 'n log(n)',
    bestCase: 'n',
    memory: '1',
    stable: true,
    method: '',
    joke: false,
  },
  {
    name: 'Shell Sort',
    function: shellSort,
    worseCase: 'n⁴ᐟ³',
    averageCase: 'n⁴ᐟ³',
    bestCase: 'n log(n)',
    memory: '1',
    stable: false,
    method: 'Insertion',
    joke: false,
  },
  {
    name: 'Tim Sort',
    function: timSort,
    worseCase: 'n log(n)',
    averageCase: 'n log(n)',
    bestCase: 'n',
    memory: 'n',
    stable: true,
    method: 'Hybrid',
    joke: false,
  },
  {
    name: 'Exchange Sort',
    function: exchangeSort,
    worseCase: 'n²',
    averageCase: 'n²',
    bestCase: 'n²',
    memory: '1',
    stable: false,
    method: 'Exchanging',
    joke: false,
  },
  {
    name: 'Cycle Sort',
    function: cycleSort,
    worseCase: 'n²',
    averageCase: 'n²',
    bestCase: 'n²',
    memory: '1',
    stable: false,
    method: 'Selection',
    joke: false,
  },
  {
    name: 'Patience Sort',
    function: patienceSort,
    worseCase: 'n log(n)',
    averageCase: 'n log(n)',
    bestCase: 'n',
    memory: '1',
    stable: false,
    method: 'Hybrid',
    joke: false,
  },
  {
    name: 'Smooth Sort',
    function: smoothSort,
    worseCase: 'n log(n)',
    averageCase: 'n log(n)',
    bestCase: 'n',
    memory: '1',
    stable: false,
    method: 'Selection',
    joke: false,
  },
  {
    name: 'Strand Sort',
    function: strandSort,
    worseCase: 'n²',
    averageCase: 'n²',
    bestCase: 'n',
    memory: 'n',
    stable: true,
    method: '',
    joke: false,
  },
  {
    name: 'Comb Sort',
    function: combSort,
    worseCase: 'n²',
    averageCase: 'n²',
    bestCase: 'n log(n)',
    memory: '1',
    stable: false,
    method: 'Exchanging',
    joke: false,
  },
  {
    name: 'Gnome Sort',
    function: gnomeSort,
    worseCase: 'n²',
    averageCase: 'n²',
    bestCase: 'n',
    memory: '1',
    stable: true,
    method: 'Exchanging',
    joke: false,
  },
  {
    name: 'Odd-Even Sort',
    function: oddEvenSort,
    worseCase: 'n²',
    averageCase: 'n²',
    bestCase: 'n',
    memory: '1',
    stable: true,
    method: 'Exchanging',
    joke: false,
  },
  {
    name: 'Pigeonhole Sort',
    function: pigeonholeSort,
    worseCase: 'n+N',
    averageCase: 'n+N',
    bestCase: 'n+N',
    memory: 'N',
    stable: true,
    method: 'Non-comparative',
    joke: false,
  },
  {
    name: 'Bucket Sort',
    function: bucketSort,
    worseCase: 'n²',
    averageCase: 'n+k',
    bestCase: 'n+k',
    memory: 'n+k',
    stable: true,
    method: 'Non-comparative',
    joke: false,
  },
  {
    name: 'Counting Sort',
    function: countingSort,
    worseCase: 'n+r',
    averageCase: 'n+r',
    bestCase: 'n+r',
    memory: 'n+r',
    stable: true,
    method: 'Non-exchanging',
    joke: false,
  },
  {
    name: 'Spread Sort',
    function: spreadSort,
    worseCase: 'n (k/s + d)',
    averageCase: 'nk/d',
    bestCase: 'n',
    memory: 'k/d 2ᵈ',
    stable: false,
    method: 'Non-exchanging',
    joke: false,
  },
  {
    name: 'Pancake Sort',
    function: pancakeSort,
    worseCase: 'n²',
    averageCase: 'n²',
    bestCase: 'n²',
    memory: '1',
    stable: false,
    method: 'Exchanging',
    joke: false,
  },
  {
    name: 'I Can\'t Believe It Can Sort',
    function: iCantBelieveItCanSort,
    worseCase: 'n²',
    averageCase: 'n²',
    bestCase: 'n²',
    memory: '1',
    stable: false,
    method: 'Exchanging',
    joke: false,
  },
  {
    name: 'Bitonic Sort',
    function: bitonicSort,
    worseCase: 'log²(n)',
    averageCase: 'log²(n)',
    bestCase: 'log²(n)',
    memory: '1',
    stable: false,
    method: 'Exchanging',
    joke: false,
  },
  {
    name: 'Bogo Sort',
    function: bogoSort,
    worseCase: 'infinite',
    averageCase: 'n * n!',
    bestCase: 'n',
    memory: '1',
    stable: false,
    method: 'Random',
    joke: false,
  },
  {
    name: 'Stooge Sort',
    function: stoogeSort,
    worseCase: 'n².71',
    averageCase: 'n².71',
    bestCase: 'n².71',
    memory: 'n',
    stable: false,
    method: 'Exchanging',
    joke: false,
  },
  {
    name: 'Slow Sort',
    function: slowSort,
    worseCase: 'nˡᵒᵍ⁽ⁿ⁾',
    averageCase: 'nˡᵒᵍ⁽ⁿ⁾',
    bestCase: 'nˡᵒᵍ⁽ⁿ⁾',
    memory: 'n',
    stable: false,
    method: 'Exchanging',
    joke: false,
  },
  {
    name: 'Stalin Sort',
    function: stalinSort,
    worseCase: 'n',
    averageCase: 'n',
    bestCase: 'n',
    memory: '1',
    stable: false,
    method: 'Deletion',
    joke: true,
  },
  {
    name: 'Sleep Sort',
    function: sleepSort,
    worseCase: 'sleep*max',
    averageCase: 'sleep*max',
    bestCase: 'sleep*max',
    memory: '1',
    stable: false,
    method: 'Sleeping',
    joke: true,
  },
  {
    name: 'Delete Sort',
    function: deleteSort,
    worseCase: 'n',
    averageCase: 'n',
    bestCase: 'n',
    memory: '1',
    stable: false,
    method: 'Deleting',
    joke: true,
  },
];

export default algorithms;